import type { Metadata } from "next";
import SideNavBar from "@/shared/ui/SideNavBar";
import Header from "@/shared/ui/Header";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ paddingLeft: "224px" }}>
        <Header />
        <div style={{ paddingTop: "72px", display: "flex" }}>
          <SideNavBar />
          <div style={{ padding: "40px" }}>{children}</div>
        </div>
      </body>
    </html>
  );
}
