import type { Metadata } from "next";
import SideNavBar from "@/shared/ui/SideNavBar";
import Header from "@/shared/ui/Header";
import { ToastProvider } from "@/shared/utils/ToastContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ToastProvider>
      <div className="layout-body">
        <Header />
        <div className="layout-content">
          <SideNavBar />
          <div className="page-content">{children}</div>
        </div>
      </div>
    </ToastProvider>
  );
}
